<!------------
--------------------------------------------- JavaScript Error Handling -----------------------------------------------<br>

===========================================================================================================================<br>
function mikeSage(){<br>
	       <br>
};         <br>
===========================================================================================================================<br>

=================================== JavaScript Errors - Throw and Try to Catch =======================================<br>

The "try" statement lets you test a block of code for errors.

The "catch" statement lets you handle the error.

The "throw" statement lets you create custom errors.

The "finally" statement lets you execute code, after try and catch, regardless of the result.

=================================================== Errors Will Happen! ===============================================<br>
When executing JavaScript code, different errors can occur.<br>
Errors can be coding errors made by the programmer, errors due to wrong input, and other unforeseeable things.<br>

we have written alert as adddlert to deliberately produce an error:

<!DOCTYPE html>
<html>
<body>
<p id="demo"></p>
<script>
try {
  adddlert("Welcome guest!");
}
catch(err) {
  document.getElementById("demo").innerHTML = err.message;
}
</script>
</body>
</html>

Note: JavaScript catches adddlert as an error, and executes the catch code to handle it.

============================================== JavaScript try and catch ===============================================<br>
The try statement allows you to define a block of code to be tested for errors while it is being executed.
The catch statement allows you to define a block of code to be executed, if an error occurs in the try block.
The JavaScript statements try and catch come in pairs:
<script>
try {
  Block of code to try
}
catch(err) {
  Block of code to handle errors
}
</script>

============================================ JavaScript Throws Errors ===============================================<br>
When an error occurs, JavaScript will normally stop and generate an error message.<br>
The technical term for this is: JavaScript will throw an exception (throw an error).<br>
Note: JavaScript will actually create an Error object with two properties: name and message.<br>

=============================================== The throw Statement ===============================================<br>
The throw statement allows you to create a custom error.
Technically you can throw an exception (throw an error).
The exception can be a JavaScript String, a Number, a Boolean or an Object:

throw "Too big";    // throw a text
throw 500;          // throw a number
If you use throw together with try and catch, you can control program flow and generate custom error messages.

============================================= Input Validation Example ===============================================<br>
This example examines input. If the value is wrong, an exception (err) is thrown.
The exception (err) is caught by the catch statement and a custom error message is displayed:

<!DOCTYPE html>
<html>
<body>
<p>Please input a number between 5 and 10:</p>

<input id="demo" type="text">
<button type="button" onclick="myFunction()">Test Input</button>
<p id="p01"></p>

<script>
function myFunction() {
  var message, x;
  message = document.getElementById("p01");
  message.innerHTML = "";
  x = document.getElementById("demo").value;
  try { 
    if(x == "")  throw "empty";
    if(isNaN(x)) throw "not a number";
    x = Number(x);
    if(x < 5)  throw "too low";
    if(x > 10)   throw "too high";
  }
  catch(err) {
    message.innerHTML = "Input is " + err;
  }
}
</script>
</body>
</html>

================================================== HTML Validation ===================================================<br>
The code above is just an example.
Modern browsers will often use a combination of JavaScript and built-in HTML validation, using predefined validation rules defined in HTML attributes:

<input id="demo" type="number" min="5" max="10" step="1">

============================================ The finally Statement ===================================================<br>
The finally statement lets you execute code, after try and catch, regardless of the result:

Syntax

<script>
try {
  Block of code to try
}
catch(err) {
  Block of code to handle errors
}
finally {
  Block of code to be executed regardless of the try / catch result
}

<!DOCTYPE html>
<html>
<body>

<p>Please input a number between 5 and 10:</p>

<input id="demo" type="text">
<button type="button" onclick="myFunction()">Test Input</button>

<p id="p01"></p>

<script>
function myFunction() {
  var message, x;
  message = document.getElementById("p01");
  message.innerHTML = "";
  x = document.getElementById("demo").value;
  try { 
    if(x == "")  throw "is empty";
    if(isNaN(x)) throw "is not a number";
    x = Number(x);
    if(x > 10)   throw "is too high";
    if(x < 5)  throw "is too low";
  }
  catch(err) {
    message.innerHTML = "Input " + err;
  }
  finally {
    document.getElementById("demo").value = "";
  }
}
</script>

</body>
</html>

============================================== The Error Object ==============================================<br>
JavaScript has a built in error object that provides error information when an error occurs.
The error object provides two useful properties: name and message.

============================================== Error Object Properties ==============================================<br>
Property	Description
name	Sets or returns an error name
message	Sets or returns an error message (a string)

============================================== Error Name Values ==============================================<br>
Six different values can be returned by the error name property:

Error Name	Description
EvalError	An error has occurred in the eval() function
RangeError	A number "out of range" has occurred
ReferenceError	An illegal reference has occurred
SyntaxError	A syntax error has occurred
TypeError	A type error has occurred
URIError	An error in encodeURI() has occurred

============================================== Eval Error ==============================================<br>
An EvalError indicates an error in the eval() function.
Newer versions of JavaScript do not throw EvalError. Use SyntaxError instead.
The six different values are described below.

====================================================== Range Error ===================================================<br>
A RangeError is thrown if you use a number that is outside the range of legal values.
For example: You cannot set the number of significant digits of a number to 500.
<!DOCTYPE html>
<html>
<body>
<h2>JavaScript Errors</h2>
<p>You cannot set the number of significant digits of a number to 500:</p>
<p id="demo">
<script>
var num = 1;
try {
  num.toPrecision(500); A number cannot have 500 significant digits
}
catch(err) {
  document.getElementById("demo").innerHTML = err.name;
}
</script>
</body>
</html>
================================================== Reference Error ===================================================<br>
A ReferenceError is thrown if you use (reference) a variable that has not been declared:

  <!DOCTYPE html>
  <html>
  <body>
  <h2>JavaScript Errors</h2>
  <p>You cannot use the value of a non-existing variable:</p>
  <p id="demo"></p>
  <script>
  var x;
  try {
    x = y + 1;
  }
  catch(err) {
    document.getElementById("demo").innerHTML = err.name;
  }
  </script>

  </body>
  </html>

=================================================== Syntax Error ===================================================<br>
A SyntaxError is thrown if you try to evaluate code with a syntax error.

<!DOCTYPE html>
<html>
<body>

<h2>JavaScript Errors</h2>
<p>You cannot evaluate code that contains a syntax error:</p>
<p id="demo"></p>

<script>
try {
  eval("alert('Hello)");
}
catch(err) {
  document.getElementById("demo").innerHTML = err.name;
}
</script>
</body>
</html>

=================================================== Type Error ===================================================<br>
A TypeError is thrown if you use a value that is outside the range of expected types:

<!DOCTYPE html>
<html>
<body>
<h2>JavaScript Errors</h2>
<p>You cannot convert a number to upper case:</p>
<p id="demo"></p>
<script>
var num = 1;
try {
  num.toUpperCase();
}
catch(err) {
  document.getElementById("demo").innerHTML = err.name;
}
</script>

</body>
</html>

============================== URI (Uniform Resource Identifier) Error ============================================<br>
A URIError is thrown if you use illegal characters in a URI function:

<!DOCTYPE html>
<html>
<body>

<h2>JavaScript Errors</h2>

<p>Some characters cannot be decoded with decodeURI():</p>

<p id="demo"></p>

<script>
try {
  decodeURI("%%%");
}
catch(err) {
  document.getElementById("demo").innerHTML = err.name;
}
</script>
</body>
</html>

====================== Non-Standard Error Object Properties ======================<br>
Mozilla and Microsoft defines some non-standard error object properties:

fileName (Mozilla)
lineNumber (Mozilla)
columnNumber (Mozilla)
stack (Mozilla)
description (Microsoft)
number (Microsoft)

Note: Do not use these properties in public web sites. They will not work in all browsers.--------->